URL_MAIN = 'https://target.my.com/dashboard'
URL_CREATE_COMPANY = 'https://target.my.com/api/v2/campaigns.json'
URL_CHECK_COMPANY = 'https://target.my.com/api/v2/campaigns.json?fields=id%2Cname%2Cdelivery%2Cprice%2Cbudget_limit%2Cbudget_limit_day%2Cpads_ots_limits%2Ccreated%2Cissues%2Cprices%2Cstatus%2Cpackage_id%2Cinterface_read_only%2Cread_only%2Cobjective%2Cuser_id%2Ctargetings__split_audience%2Ctargetings__pads%2Cenable_utm%2Cutm%2Cage_restrictions%2Cpackage_priced_event_type%2Cautobidding_mode&sorting=-id&limit=10&offset=0&_status__in=active&_user_id__in=11726496'
URL_DELETE_COMPANY = 'https://target.my.com/api/v2/campaigns/mass_action.json'
URL_NEW_SEGMENT = 'https://target.my.com/api/v2/remarketing/segments.json?fields=relations__object_type,relations__object_id,relations__params,relations__params__score,relations__id,relations_count,id,name,pass_condition,created,campaign_ids,users,flags'
URL_DELETE_SEGMENT = 'https://target.my.com/api/v1/remarketing/mass_action/delete.json'
URL_POST_IMAGE = 'https://target.my.com/api/v2/content/static.json'
URL_GET_ID = 'https://target.my.com/api/v2/campaign_objective/traffic/urls.json'

URL_AUTH = 'https://auth-ac.my.com/auth?lang=ru&nosavelogin=0'
URL_PARAMS_FROM = 'http://target.my.com/auth/mycom?state=target_login%3D1%26ignore_opener%3D1'
URL_FOR_LOCATION ='https://auth-ac.my.com/sdc?from=http%3A%2F%2Ftarget.my.com%2Fauth%2Fmycom%3Fstate%3Dtarget_login%253D1%2526ignore_opener%253D1'
URL_FOR_Z = 'https://target.my.com/api/v2/localization_components.json?lang=en,ru'
URL_FOR_SDC = 'https://target.my.com/sdc'
URL_CSRF = 'https://target.my.com/csrf/'
